{% set name = "ordered-set" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ordered-set-{{ version }}.tar.gz
  sha256: 694a8e44c87657c59292ede72891eb91d34131f6531463aab3009191c77364a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - python >={{ python_min }}

test:
  imports:
    - ordered_set
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/LuminosoInsight/ordered-set
  license: MIT
  license_file: MIT-LICENSE
  summary: A MutableSet that remembers its order, so that every entry has an index.


extra:
  recipe-maintainers:
    - benjwadams
    - ocefpaf
